### ISSUE TITLE
Possible enhancements

### ISSUE THREAD

**Issue by dominikmicuta** [mrfatworm/ZZZ-Archive#3]
I checked the code and noticed you pass AdaptiveLayoutType and ContentType a lot.
Maybe CompositionLocalProvider could be used to simplify this:
https://developer.android.com/develop/ui/compose/compositionlocal

I personally wrap navigation into interface and pass it to ViewModels with [koinViewModel -> parameters] to avoid a lot of navigation lambda passing as well but this is more like a personal decision.

**Comment by mrfatworm** [comment]
Thank you for your feedback! It's very helpful, and I will work on making adjustments.

By the way, this is my first time maintaining an open-source project. Do you have any advice or suggestions on what I should pay attention to? For example, are there any specific documents I should provide?

**Comment by mrfatworm** [comment]
@dominikmicuta , thank you for your suggestion! 
The code structure has become much cleaner now.

**Comment by felipecastilhos** [comment]
Hey @mrfatworm I think you can close this issue since it was resolved on this PR https://github.com/mrfatworm/ZZZ-Archive/pull/4

btw great job ✌🏼

**Comment by mrfatworm** [comment]
@felipecastilhos Thank you! I’m still learning these GitHub features. 😅

**Comment by felipecastilhos** [comment]
@mrfatworm maybe you can take look at this: https://github.blog/news-insights/product-news/closing-issues-via-commit-messages/
