### ISSUE TITLE
Inconsistency usage of Dimens

### ISSUE THREAD

**Issue by felipecastilhos** [mrfatworm/ZZZ-Archive#8]
I was experimenting with your project and noticed that your AppTheme includes a Dimens provider, which defines some padding values. However, these paddings are not widely used across your components.

I believe the main issue is the use of very specific names tied to where the paddings are applied, rather than adopting a more semantic approach aligned with a Design System perspective.

To improve this, you might consider using broader, more general names for the paddings, such as:
```
object Dimens {
    object Spacings {
        const val None = 0
        const val ExtraSmall = 4
        const val Small = 8
        const val Medium = 16
        const val Large = 24
        const val ExtraLarge = 32
        const val DoubleExtraLarge = 64
    }
}
```

By doing this, you can reduce duplicated values in your Dimens and achieve greater consistency in spacing usage throughout your application. Also some could be add some other Dimens values like border radius, sizes...

Example where isn't being used: `Buttons.kt`

**Comment by mrfatworm** [comment]
Hi @felipecastilhos ,
Thank you for your suggestion! I agree with you

...However, implementing this change involves a fairly large scope. It would not only require adjustments in the codebase but also updates to all corresponding elements in Figma. This might take some time to fully implement. 😵‍💫

One concern I have is about future team members who might join the project but don’t have access to Figma Pro and its Dev Mode. Without Dev Mode, they would only see raw spacing values instead of the semantic names, which could lead to confusion and difficulties in maintaining consistency.

![image](https://github.com/user-attachments/assets/052b6048-1baf-44d1-a656-f0e8e5951ed7)
Select a element and click `option` to show padding

**Comment by felipecastilhos** [comment]
Yea. It makes sense. 

One thing that I was thinking about, maybe it would be good to organize only on codebase. But usually the designs are the part that propagate wrong values after all, so it wouldn't bring so much value besides making your code looking more semantic. I mean, avoiding using hardcoded values and getting the values from the theme somehow.

It sucks that penpot doesn't have a great token system yet. But i think soon we'll have it. It's going to be great for open source projects.

Btw, this was a just a suggestion that if properly handled your code would look way more neat than already is. It's hard to find a full project with design files and code and it's really cool to see that you come so far soloing for the most part.

On my side you can close this thread if you want or if you want to keep this rolling for a while it's fine too.

**Comment by mrfatworm** [comment]
I'm glad we could have this discussion—it’s been really insightful and valuable for improving the project.

I’d like to share some of my own experiences as well. This afternoon, I reviewed my old project and realized I had tried a similar approach before, defining things like `medium = 8.dp` and `large = 16.dp`. However, I encountered a few challenges during development:

- When I see 16.dp in the design files, I often forget that it maps to `large = 16.dp`, and I have to open Dimens.kt to double-check (probably a personal issue 😂).
- Even after defining basic sizes like 4, 8, 16, 32, 64, I frequently find myself needing to add values like 2, 6, 24, 48, which leads to constant adjustments and renaming.
- If the purpose is to enable overall UI scaling, there are parts I can’t easily define, such as NavigationBarItem in Material 3 components, unless I fully customize their sizes.

![Frame 1](https://github.com/user-attachments/assets/4772b7a9-3967-4ee6-a390-e06ce1d40b84)


Of course, it might be that I haven’t discovered a better way to approach this yet. If you have related experiences or examples, I’d love to hear about them!


BTW, this was my first time hearing about Penpot—it’s so cooooool

**Comment by felipecastilhos** [comment]
Oh, awesome that you brought examples! I tried to keep my answer short, but it’s tricky since we’re diving into complex topics that don’t have a one-size-fits-all solution 😆.

I’ve worked on several design system projects over the years for different companies, and what I’ve observed is that the approach varies a lot from project to project—even within the same project, teams might experiment with different strategies.

Sometimes, the structures you’re building are primarily for your own team’s use, and other times, they’re for external teams or users. This distinction matters because it influences how you perceive those decisions and how quickly you can adapt to changes.

That said, since this project is mostly maintained by you right now, I’d recommend going with whatever works best for **you** at this stage.

Here are some thoughts from my experiences with both approaches:

First Image: using like that is hard to maintain if you are going to changing a lot, because it's hard to find new names based on what you had (fourtyLarge, as example I think it dindn't clarify too much how it helps in the content hierarchy), and also adding things in between (for example: will it be halfExtraLarge? lol). But if you're not going to iterate too much it's a good fit and it could help to understand more semantically the relation between elements if you have the right names, like: On between Titles and components are always large spaces, elements always are at least medium size different from each other.

Second image: This approach is close to hardcoding but adds abstraction. You get the benefit of centralizing constants, but if you shift your spacing scheme (e.g., to multiples of 3), you'll need to refactor since it  require changing all constants names. However, this abstraction helps make it clear when you’re working with spacings specifically, avoiding accidental overlap with other contexts like component heights.

Ultimately, all approaches have trade-offs, and it boils down to how flexible or stable (and sometimes flexibility is stability for the project) your design system needs to be in the near future.

I think you as a design/software engineer should what works best for you to keep all your figma docs most up-to-date with the codebase. Because in the end the source of truth will be always the code and it will dictate the efforts to do your changes.

oof, sorry for the wall of text 😅

**Comment by felipecastilhos** [comment]
Oh, and if you like the subject, you might enjoy this book if you haven’t come across it already: Design Systems: A Practical Guide to Creating Design Languages for Digital Products by Alla Kholmatova.

**Comment by mrfatworm** [comment]
I agree that consistency and team alignment are the most important things—there might not be a perfect solution.

I’ll try making some adjustments, starting with Components.

Thanks again for your helpful input! 😊
